### ISSUE TITLE
一个不用手动抓logintoken的方法

### ISSUE THREAD

**Issue by MOLIzhang** [cyugwan/yibancheck#1]
https://github.com/Crazyokd/yiban-auto
模拟易班校本化登陆后获取'yiban_user_token'，不知道是不是和***的logintoken一样？

**Comment by babattata-ta** [comment]
那个接口我试过，还没有找到解决方法。

未来会尝试用这个接口

**Comment by MOLIzhang** [comment]
logintoken好像不存在过期时间 只要有重新打开一次ygj授权就可以续期了
